name: null
favicon: null
layout_spectrum: 0.9765322206076235
typography_spectrum: 0.8283818543422967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4054366908967495
  lightness: 0.6336949202232063
  saturation: 0.4009065078571439
  rhythmicContrast: 0.768701487686485
purpose: []
